import MockupImage from '../assets/pic.jpg';
import MockupImage1 from '../assets/news.jpg';
import MockupImage2 from '../assets/date.jpg';

const products = [
  {
    id: 1,
    name: "iPhone 13 4GB RAM/64-128GB STORAGE",
    category: "Smartphone",
    brand: "Apple",
    model: "iPhone 13",
    priceRange: "799-1099",
    image: MockupImage,
    description:
      "The iPhone 13 features a stunning design, advanced dual-camera system, and the powerful A15 Bionic chip. Experience smooth performance and 5G connectivity.",
    price: 799.00,
    availability: "In Stock",
    shippingInfo: "Ships within 1-2 business days.",
    discount: "5% off for Apple members",
    rating: 4.8,
    reviews: 512,
    reviewsArray: [
      { user: "Alice Johnson", rating: 5, comment: "The camera quality is amazing! Totally worth it." },
      { user: "Bob Williams", rating: 4, comment: "Great phone, but the screen could be a bit brighter." },
    ],
    variations: [
      { ram: "4GB", storage: "64GB", color: "Black", price: 799, image: MockupImage1 },
      { ram: "6GB", storage: "256GB", color: "White", price: 1099, image: MockupImage2 },
    ],
    gallery: [MockupImage, MockupImage1, MockupImage2],
    dimensions: "146.7 x 71.5 x 7.65 mm",
    weight: "173g",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "14 days return policy",
    faq: [
      { question: "Does this iPhone support Face ID?", answer: "Yes, it comes with Face ID support." },
      { question: "Is this model water-resistant?", answer: "Yes, it has an IP68 rating for water and dust resistance." },
    ],
    tags: { brandNew: true, popular: true, featured: true, newArrival: false },
  },


  {
    id: 30,
    name: "iPhone 13 4GB RAM/64-128GB STORAGE",
    category: "Smartphone",
    brand: "Apple",
    model: "iPhone 13",
    priceRange: "799-1099",
    image: MockupImage,
    description:
      "The iPhone 13 features a stunning design, advanced dual-camera system, and the powerful A15 Bionic chip. Experience smooth performance and 5G connectivity.",
    price: 799.00,
    availability: "In Stock",
    shippingInfo: "Ships within 1-2 business days.",
    discount: "5% off for Apple members",
    rating: 4.8,
    reviews: 512,
    reviewsArray: [
      { user: "Alice Johnson", rating: 5, comment: "The camera quality is amazing! Totally worth it." },
      { user: "Bob Williams", rating: 4, comment: "Great phone, but the screen could be a bit brighter." },
    ],
    variations: [
      { ram: "4GB", storage: "64GB", color: "Black", price: 799, image: MockupImage1 },
      { ram: "6GB", storage: "256GB", color: "White", price: 1099, image: MockupImage2 },
    ],
    gallery: [MockupImage, MockupImage1, MockupImage2],
    dimensions: "146.7 x 71.5 x 7.65 mm",
    weight: "173g",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "14 days return policy",
    faq: [
      { question: "Does this iPhone support Face ID?", answer: "Yes, it comes with Face ID support." },
      { question: "Is this model water-resistant?", answer: "Yes, it has an IP68 rating for water and dust resistance." },
    ],
    tags: { brandNew: true, popular: true, featured: true, newArrival: false },
  },
  {
    id: 2,
    name: "Samsung Galaxy S21",
    category: "Smartphone",
    brand: "Samsung",
    model: "Galaxy S21",
    priceRange: "799-999",
    image: MockupImage,
    description: "The Samsung Galaxy S21 offers an impressive camera system, 8K video recording, and a stunning Dynamic AMOLED 2X display.",
    price: 899.00,
    availability: "In Stock",
    shippingInfo: "Ships within 3-4 business days.",
    discount: "10% off on trade-in",
    rating: 4.7,
    reviews: 412,
    reviewsArray: [
      { user: "Michael Brown", rating: 5, comment: "Amazing display and fast performance!" },
      { user: "Lisa White", rating: 4, comment: "Great phone, but it’s a bit pricey." },
    ],
    variations: [
      { ram: "8GB", storage: "128GB", color: "Phantom Gray", price: "$799", image: MockupImage },
      { ram: "12GB", storage: "256GB", color: "Phantom Silver", price: "$999", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "151.7 x 71.2 x 7.9 mm",
    weight: "169g",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Does it support wireless charging?", answer: "Yes, it supports fast wireless charging." },
      { question: "Is the camera capable of 8K recording?", answer: "Yes, it records in 8K resolution." },
    ],
    tags: { brandNew: true, popular: true, featured: false, newArrival: true },
  },
  {
    id: 3,
    name: "Google Pixel 6",
    category: "Smartphone",
    brand: "Google",
    model: "Pixel 6",
    priceRange: "699-899",
    image: MockupImage,
    description: "The Google Pixel 6 comes with a powerful Tensor chip, exceptional camera, and seamless integration with Google's services.",
    price: 799.00,
    availability: "In Stock",
    shippingInfo: "Ships within 2-3 business days.",
    discount: "Free Google Nest Mini with purchase",
    rating: 4.6,
    reviews: 315,
    reviewsArray: [
      { user: "Sarah Clark", rating: 5, comment: "Best Android phone for photography!" },
      { user: "Tom Harris", rating: 4, comment: "Great software, but lacks in battery life." },
    ],
    variations: [
      { ram: "8GB", storage: "128GB", color: "Stormy Black", price: "$699", image: MockupImage },
      { ram: "12GB", storage: "256GB", color: "Sorta Seafoam", price: "$899", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "158.6 x 74.8 x 8.9 mm",
    weight: "207g",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Does it have an in-display fingerprint sensor?", answer: "Yes, it does." },
      { question: "Is the screen OLED?", answer: "Yes, it features an OLED display." },
    ],
    tags: { brandNew: false, popular: true, featured: false, newArrival: true },
  },
  // Continue with more smartphone products...
{
    id: 4,
    name: "MacBook Pro 16-inch",
    category: "Laptop",
    brand: "Apple",
    model: "MacBook Pro 16",
    priceRange: "2399-2799",
    image: MockupImage,
    description:
      "The MacBook Pro 16-inch comes with the powerful M1 Pro chip, an immersive Retina display, and an exceptional battery life. Ideal for professionals and creatives.",
    price: 2499.00,
    availability: "In Stock",
    shippingInfo: "Ships within 3-4 business days.",
    discount: "5% off for students",
    rating: 4.9,
    reviews: 620,
    reviewsArray: [
      { user: "Jessica Lee", rating: 5, comment: "The best laptop for heavy tasks and video editing." },
      { user: "Mark Evans", rating: 4, comment: "Fantastic performance but on the pricier side." },
    ],
    variations: [
      { ram: "16GB", storage: "512GB", color: "Space Gray", price: "$2399", image: MockupImage },
      { ram: "32GB", storage: "1TB", color: "Silver", price: "$2799", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "355.7 x 247.1 x 16.2 mm",
    weight: "2.1 kg",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "14 days return policy",
    faq: [
      { question: "Does the MacBook Pro support Thunderbolt 4?", answer: "Yes, it has three Thunderbolt 4 ports." },
      { question: "Is the screen mini-LED?", answer: "Yes, it features a Liquid Retina XDR display with mini-LED technology." },
    ],
    tags: { brandNew: true, popular: true, featured: true, newArrival: false },
  },
  {
    id: 5,
    name: "Dell XPS 13",
    category: "Laptop",
    brand: "Dell",
    model: "XPS 13",
    priceRange: "999-1399",
    image: MockupImage,
    description:
      "The Dell XPS 13 offers a stunning 13.4-inch display, excellent build quality, and impressive performance packed in a slim design.",
    price: 1199.00,
    availability: "In Stock",
    shippingInfo: "Ships within 2-3 business days.",
    discount: "Free shipping on all orders",
    rating: 4.7,
    reviews: 412,
    reviewsArray: [
      { user: "Olivia Green", rating: 5, comment: "Perfect ultrabook for daily use and travel." },
      { user: "Henry Clark", rating: 4, comment: "Great design, but the battery could last longer." },
    ],
    variations: [
      { ram: "8GB", storage: "256GB", color: "Platinum Silver", price: "$999", image: MockupImage },
      { ram: "16GB", storage: "512GB", color: "Frost White", price: "$1399", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "296 x 199 x 14.8 mm",
    weight: "1.2 kg",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Does it come with a 4K display option?", answer: "Yes, a 4K UHD+ touchscreen option is available." },
      { question: "Does it have a webcam?", answer: "Yes, it comes with a 720p HD webcam." },
    ],
    tags: { brandNew: true, popular: true, featured: false, newArrival: false },
  },
  {
    id: 6,
    name: "HP Spectre x360",
    category: "Laptop",
    brand: "HP",
    model: "Spectre x360",
    priceRange: "1099-1599",
    image: MockupImage,
    description:
      "The HP Spectre x360 is a 2-in-1 laptop that combines power and flexibility with a touch-enabled 4K OLED display and an Intel Core i7 processor.",
    price: 1299.00,
    availability: "In Stock",
    shippingInfo: "Ships within 3-4 business days.",
    discount: "10% off with HP Rewards",
    rating: 4.8,
    reviews: 378,
    reviewsArray: [
      { user: "Andrew Smith", rating: 5, comment: "Amazing display and great versatility for creative work." },
      { user: "Emily Brown", rating: 4, comment: "Performance is fantastic, but it's a bit heavy for a convertible." },
    ],
    variations: [
      { ram: "8GB", storage: "256GB", color: "Nightfall Black", price: "$1099", image: MockupImage },
      { ram: "16GB", storage: "512GB", color: "Poseidon Blue", price: "$1599", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "307 x 194.5 x 16.9 mm",
    weight: "1.3 kg",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Can the display rotate 360 degrees?", answer: "Yes, the hinge allows 360-degree rotation for tablet mode." },
      { question: "Does it support stylus input?", answer: "Yes, it supports the HP Tilt Pen." },
    ],
    tags: { brandNew: false, popular: true, featured: false, newArrival: true },
  },
  {
    id: 7,
    name: "Lenovo ThinkPad X1 Carbon",
    category: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon",
    priceRange: "1399-1899",
    image: MockupImage,
    description:
      "The Lenovo ThinkPad X1 Carbon is a business laptop with a robust design, legendary keyboard, and long battery life, perfect for productivity.",
    price: 1499.00,
    availability: "In Stock",
    shippingInfo: "Ships within 1-2 business days.",
    discount: "5% off for business purchases",
    rating: 4.7,
    reviews: 295,
    reviewsArray: [
      { user: "David Martin", rating: 5, comment: "Solid build, and the keyboard is the best in its class." },
      { user: "Sophia Harris", rating: 4, comment: "Great laptop, but the screen could be brighter." },
    ],
    variations: [
      { ram: "16GB", storage: "512GB", color: "Black", price: "$1399", image: MockupImage },
      { ram: "32GB", storage: "1TB", color: "Storm Gray", price: "$1899", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "323 x 217 x 14.9 mm",
    weight: "1.13 kg",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "14 days return policy",
    faq: [
      { question: "Does it come with LTE support?", answer: "Yes, it has an optional LTE modem for connectivity on the go." },
      { question: "Is the keyboard backlit?", answer: "Yes, the keyboard is backlit." },
    ],
    tags: { brandNew: true, popular: false, featured: true, newArrival: true },
  },
  {
    id: 8,
    name: "Asus ROG Zephyrus G15",
    category: "Laptop",
    brand: "Asus",
    model: "ROG Zephyrus G15",
    priceRange: "1599-1999",
    image: MockupImage,
    description:
      "The Asus ROG Zephyrus G15 is a powerful gaming laptop with an AMD Ryzen 9 processor and NVIDIA RTX 3080 graphics, delivering top-notch gaming performance.",
    price: 1799.00,
    availability: "In Stock",
    shippingInfo: "Ships within 3-5 business days.",
    discount: "5% off for ROG members",
    rating: 4.9,
    reviews: 290,
    reviewsArray: [
      { user: "James Robinson", rating: 5, comment: "The best gaming laptop in terms of performance and design." },
      { user: "Mia King", rating: 4, comment: "Great for gaming, but it gets a bit hot under load." },
    ],
    variations: [
      { ram: "16GB", storage: "1TB", color: "Eclipse Gray", price: "$1599", image: MockupImage },
      { ram: "32GB", storage: "2TB", color: "Moonlight White", price: "$1999", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "355 x 243 x 19.9 mm",
    weight: "1.9 kg",
    warranty: "2 years manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Does it have an RGB keyboard?", answer: "Yes, it features per-key RGB lighting." },
      { question: "Can it handle VR gaming?", answer: "Yes, it's fully VR-ready." },
    ],
    tags: { brandNew: true, popular: true, featured: true, newArrival: true },
  },
  {
    id: 9,
    name: "Acer Swift 3",
    category: "Laptop",
    brand: "Acer",
    model: "Swift 3",
    priceRange: "599-899",
    image: MockupImage,
    description:
      "The Acer Swift 3 is a budget-friendly ultrabook that offers great performance, a bright display, and long battery life in a lightweight design.",
    price: 699.00,
    availability: "In Stock",
    shippingInfo: "Ships within 2-3 business days.",
    discount: "10% off for students",
    rating: 4.5,
    reviews: 220,
    reviewsArray: [
      { user: "Hannah Brooks", rating: 5, comment: "Amazing value for the price." },
      { user: "Daniel White", rating: 4, comment: "Solid performance but lacks premium build materials." },
    ],
    variations: [
      { ram: "8GB", storage: "256GB", color: "Silver", price: "$599", image: MockupImage },
      { ram: "16GB", storage: "512GB", color: "Gold", price: "$899", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "319.5 x 217 x 15.9 mm",
    weight: "1.19 kg",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Is it good for light gaming?", answer: "It can handle light gaming but is not designed for heavy gaming." },
      { question: "Does it have an HDMI port?", answer: "Yes, it includes an HDMI 2.0 port." },
    ],
    tags: { brandNew: false, popular: false, featured: false, newArrival: false },
  },

  {
    id: 10,
    name: "Samsung QLED 8K Smart TV",
    category: "TV",
    brand: "Samsung",
    model: "Q900T",
    priceRange: "2999-3999",
    image: MockupImage,
    description:
      "The Samsung QLED 8K Smart TV offers stunning 8K resolution, deep blacks, and vibrant colors with Quantum Dot technology, delivering a cinematic experience at home.",
    price: 3499.00,
    availability: "In Stock",
    shippingInfo: "Ships within 5-7 business days.",
    discount: "10% off for Samsung members",
    rating: 4.8,
    reviews: 198,
    reviewsArray: [
      { user: "Chris Lee", rating: 5, comment: "The picture quality is phenomenal! 8K is the future." },
      { user: "Karen Smith", rating: 4, comment: "Excellent TV, but the price is quite steep." },
    ],
    variations: [
      { size: "65-inch", price: "$2999", image: MockupImage },
      { size: "75-inch", price: "$3999", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage, MockupImage],
    dimensions: "1446 x 892 x 25 mm",
    weight: "38 kg",
    warranty: "2 years manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Does it support HDMI 2.1?", answer: "Yes, it features HDMI 2.1 for the latest gaming consoles." },
      { question: "Is it compatible with Alexa?", answer: "Yes, it supports Alexa, Google Assistant, and Bixby." },
    ],
    tags: { brandNew: true, popular: true, featured: true, newArrival: false },
  },
  {
    id: 11,
    name: "LG OLED CX 55-inch 4K TV",
    category: "TV",
    brand: "LG",
    model: "OLED55CXPUA",
    priceRange: "1499-1999",
    image: MockupImage,
    description:
      "The LG OLED CX features self-lit pixels for perfect black, stunning color accuracy, and a responsive gaming experience with support for G-SYNC and FreeSync.",
    price: 1799.00,
    availability: "In Stock",
    shippingInfo: "Ships within 3-5 business days.",
    discount: "5% off for first-time buyers",
    rating: 4.9,
    reviews: 342,
    reviewsArray: [
      { user: "Ben Parker", rating: 5, comment: "The best OLED TV on the market. The picture is surreal." },
      { user: "Sarah Gomez", rating: 5, comment: "Perfect for gaming and movies. Love the deep blacks!" },
    ],
    variations: [
      { size: "55-inch", price: "$1499", image: MockupImage },
      { size: "65-inch", price: "$1999", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "1228 x 707 x 46.9 mm",
    weight: "23 kg",
    warranty: "2 years manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Does it support Dolby Atmos?", answer: "Yes, it supports Dolby Atmos and Dolby Vision." },
      { question: "Is it good for gaming?", answer: "Yes, it has a 120Hz refresh rate and HDMI 2.1 for gaming." },
    ],
    tags: { brandNew: true, popular: true, featured: true, newArrival: true },
  },
  {
    id: 12,
    name: "Sony BRAVIA XR A80J OLED TV",
    category: "TV",
    brand: "Sony",
    model: "A80J",
    priceRange: "1899-2499",
    image: MockupImage,
    description:
      "The Sony BRAVIA XR A80J delivers stunning OLED visuals with deep blacks and vibrant colors, powered by Sony's Cognitive Processor XR for a next-gen viewing experience.",
    price: 2299.00,
    availability: "In Stock",
    shippingInfo: "Ships within 3-5 business days.",
    discount: "5% off for PlayStation owners",
    rating: 4.7,
    reviews: 276,
    reviewsArray: [
      { user: "Michael Brown", rating: 5, comment: "Outstanding picture quality with great sound." },
      { user: "Lilly Adams", rating: 4, comment: "Excellent TV but a bit expensive compared to other OLEDs." },
    ],
    variations: [
      { size: "55-inch", price: "$1899", image: MockupImage },
      { size: "65-inch", price: "$2499", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "1448 x 833 x 53 mm",
    weight: "24.2 kg",
    warranty: "2 years manufacturer warranty",
    returnPolicy: "14 days return policy",
    faq: [
      { question: "Does it support 4K 120Hz?", answer: "Yes, it supports 4K at 120Hz for gaming." },
      { question: "Is it compatible with Apple AirPlay?", answer: "Yes, it supports Apple AirPlay and HomeKit." },
    ],
    tags: { brandNew: false, popular: true, featured: false, newArrival: false },
  },
  {
    id: 13,
    name: "TCL 6-Series Roku TV 65-inch",
    category: "TV",
    brand: "TCL",
    model: "65R635",
    priceRange: "999-1299",
    image: MockupImage,
    description:
      "The TCL 6-Series combines stunning 4K HDR and Dolby Vision with the Roku platform for an exceptional smart TV experience at a great price.",
    price: 1099.00,
    availability: "In Stock",
    shippingInfo: "Ships within 4-6 business days.",
    discount: "10% off for new users",
    rating: 4.6,
    reviews: 195,
    reviewsArray: [
      { user: "Emma Scott", rating: 5, comment: "Best value for money. Excellent picture quality!" },
      { user: "John Davis", rating: 4, comment: "Good TV but the sound could be better." },
    ],
    variations: [
      { size: "55-inch", price: "$999", image: MockupImage },
      { size: "65-inch", price: "$1299", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "1448 x 832 x 73 mm",
    weight: "24 kg",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Does it support Dolby Vision?", answer: "Yes, it supports Dolby Vision HDR." },
      { question: "Is it Roku-enabled?", answer: "Yes, it comes with Roku built-in." },
    ],
    tags: { brandNew: false, popular: true, featured: true, newArrival: false },
  },
  {
    id: 14,
    name: "Vizio P-Series Quantum X 75-inch",
    category: "TV",
    brand: "Vizio",
    model: "P75QX-H1",
    priceRange: "1799-2299",
    image: MockupImage,
    description:
      "The Vizio P-Series Quantum X features stunning 4K UHD with Quantum Dot technology and 240 local dimming zones for the ultimate contrast and brightness control.",
    price: 1999.00,
    availability: "In Stock",
    shippingInfo: "Ships within 5-7 business days.",
    discount: "5% off for Vizio VIP members",
    rating: 4.7,
    reviews: 310,
    reviewsArray: [
      { user: "Lucas Turner", rating: 5, comment: "Incredible brightness and amazing picture quality." },
      { user: "Isabella Lewis", rating: 4, comment: "Great TV for movies, but the interface is a bit slow." },
    ],
    variations: [
      { size: "65-inch", price: "$1799", image: MockupImage },
      { size: "75-inch", price: "$2299", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "1673 x 960 x 72 mm",
    weight: "37 kg",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "14 days return policy",
    faq: [
      { question: "Does it support HDR10+?", answer: "Yes, it supports HDR10+, Dolby Vision, and HLG." },
      { question: "Is it good for gaming?", answer: "Yes, it has a 120Hz refresh rate and HDMI 2.1 for gaming." },
    ],
    tags: { brandNew: true, popular: false, featured: false, newArrival: true },
  },
  {
    id: 15,
    name: "Hisense U8G 55-inch Android TV",
    category: "TV",
    brand: "Hisense",
    model: "55U8G",
    priceRange: "799-999",
    image: MockupImage,
    description:
      "The Hisense U8G offers premium 4K HDR with Dolby Vision and an Android TV platform for a smart experience at an affordable price.",
    price: 899.00,
    availability: "In Stock",
    shippingInfo: "Ships within 3-5 business days.",
    discount: "10% off for first-time buyers",
    rating: 4.5,
    reviews: 165,
    reviewsArray: [
      { user: "Oliver Harris", rating: 5, comment: "Amazing TV for the price. Dolby Vision looks great!" },
      { user: "Sophie Walker", rating: 4, comment: "Good TV but the remote could be better." },
    ],
    variations: [
      { size: "55-inch", price: "$799", image: MockupImage },
      { size: "65-inch", price: "$999", image: MockupImage },
    ],
    gallery: [MockupImage, MockupImage],
    dimensions: "1230 x 707 x 78 mm",
    weight: "18.9 kg",
    warranty: "1 year manufacturer warranty",
    returnPolicy: "30 days return policy",
    faq: [
      { question: "Does it run on Android TV?", answer: "Yes, it comes with Android TV built-in." },
      { question: "Is it good for streaming?", answer: "Yes, it supports all major streaming apps like Netflix, Hulu, and Disney+." },
    ],
    tags: { brandNew: false, popular: true, featured: false, newArrival: false },
  },

    {
      id: 16,
      name: "Apple AirPods Pro (2nd Gen)",
      category: "Accessories",
      brand: "Apple",
      model: "AirPods Pro",
      priceRange: "199-249",
      image: MockupImage,
      description:
        "The Apple AirPods Pro offer active noise cancellation, transparency mode, and spatial audio for an immersive sound experience. Now with improved battery life and MagSafe charging.",
      price: 229.00,
      availability: "In Stock",
      shippingInfo: "Ships within 1-2 business days.",
      discount: "5% off for Apple Music subscribers",
      rating: 4.9,
      reviews: 1021,
      reviewsArray: [
        { user: "Jessica Clark", rating: 5, comment: "Amazing sound and noise cancellation!" },
        { user: "David Evans", rating: 4, comment: "Great product but expensive for wireless earbuds." },
      ],
      variations: [
        { color: "White", price: "$229", image: MockupImage },
      ],
      gallery: [MockupImage, MockupImage],
      dimensions: "21.8 x 24 x 30.9 mm",
      weight: "5.4g (each earbud)",
      warranty: "1 year manufacturer warranty",
      returnPolicy: "14 days return policy",
      faq: [
        { question: "Do they support wireless charging?", answer: "Yes, they support MagSafe and Qi wireless charging." },
        { question: "Are they water-resistant?", answer: "Yes, they are IPX4 water and sweat-resistant." },
      ],
      tags: { brandNew: true, popular: true, featured: true, newArrival: false },
    },
    {
      id: 17,
      name: "Samsung Galaxy Buds2 Pro",
      category: "Accessories",
      brand: "Samsung",
      model: "Galaxy Buds2 Pro",
      priceRange: "149-199",
      image: MockupImage,
      description:
        "Samsung Galaxy Buds2 Pro offer Hi-Fi sound, active noise cancellation, and enhanced comfort. Designed for seamless connectivity with Samsung Galaxy devices.",
      price: 179.00,
      availability: "In Stock",
      shippingInfo: "Ships within 2-3 business days.",
      discount: "10% off for Galaxy users",
      rating: 4.7,
      reviews: 412,
      reviewsArray: [
        { user: "Liam Wilson", rating: 5, comment: "Excellent sound quality, perfect for daily use." },
        { user: "Emily Davis", rating: 4, comment: "Comfortable to wear but could improve the battery life." },
      ],
      variations: [
        { color: "Graphite", price: "$179", image: MockupImage },
      ],
      gallery: [MockupImage, MockupImage],
      dimensions: "20.9 x 19.9 x 21.1 mm",
      weight: "5g (each earbud)",
      warranty: "1 year manufacturer warranty",
      returnPolicy: "30 days return policy",
      faq: [
        { question: "Do they support wireless charging?", answer: "Yes, they support wireless charging." },
        { question: "Are they good for workouts?", answer: "Yes, they are IPX7-rated for water and sweat resistance." },
      ],
      tags: { brandNew: true, popular: false, featured: false, newArrival: true },
    },
    {
      id: 18,
      name: "Anker PowerCore 10000 Portable Charger",
      category: "Accessories",
      brand: "Anker",
      model: "PowerCore 10000",
      priceRange: "29-49",
      image: MockupImage,
      description:
        "The Anker PowerCore 10000 is a lightweight, compact power bank with 10,000mAh capacity, capable of charging most smartphones multiple times.",
      price: 39.00,
      availability: "In Stock",
      shippingInfo: "Ships within 1-2 business days.",
      discount: "10% off for new customers",
      rating: 4.8,
      reviews: 658,
      reviewsArray: [
        { user: "Ethan Anderson", rating: 5, comment: "Compact and powerful. Ideal for traveling!" },
        { user: "Olivia White", rating: 4, comment: "Great power bank, but lacks fast charging support." },
      ],
      variations: [
        { color: "Black", price: "$39", image: MockupImage },
      ],
      gallery: [MockupImage, MockupImage],
      dimensions: "92 x 60 x 22 mm",
      weight: "180g",
      warranty: "18 months manufacturer warranty",
      returnPolicy: "30 days return policy",
      faq: [
        { question: "Does it support fast charging?", answer: "No, it offers standard charging speeds." },
        { question: "Can it charge tablets?", answer: "Yes, it can charge tablets but at a slower speed." },
      ],
      tags: { brandNew: false, popular: true, featured: true, newArrival: false },
    },
    {
      id: 19,
      name: "Logitech MX Master 3 Wireless Mouse",
      category: "Accessories",
      brand: "Logitech",
      model: "MX Master 3",
      priceRange: "79-99",
      image: MockupImage,
      description:
        "The Logitech MX Master 3 is an ergonomic wireless mouse designed for productivity, featuring customizable buttons, a precise scroll wheel, and multi-device support.",
      price: 89.00,
      availability: "In Stock",
      shippingInfo: "Ships within 1-2 business days.",
      discount: "5% off for students",
      rating: 4.9,
      reviews: 872,
      reviewsArray: [
        { user: "Mark Harris", rating: 5, comment: "Best mouse for productivity. Super smooth and precise." },
        { user: "Sophia Walker", rating: 4, comment: "Excellent mouse but a bit pricey." },
      ],
      variations: [
        { color: "Graphite", price: "$89", image: MockupImage },
      ],
      gallery: [MockupImage, MockupImage],
      dimensions: "124.9 x 84.3 x 51 mm",
      weight: "141g",
      warranty: "1 year manufacturer warranty",
      returnPolicy: "30 days return policy",
      faq: [
        { question: "Does it work on Mac?", answer: "Yes, it's compatible with macOS and Windows." },
        { question: "Is it rechargeable?", answer: "Yes, it has a built-in rechargeable battery." },
      ],
      tags: { brandNew: true, popular: true, featured: false, newArrival: false },
    },
    {
      id: 20,
      name: "Belkin 3-in-1 Wireless Charging Pad",
      category: "Accessories",
      brand: "Belkin",
      model: "BOOST↑CHARGE",
      priceRange: "119-149",
      image: MockupImage,
      description:
        "The Belkin 3-in-1 Wireless Charging Pad allows you to charge your iPhone, Apple Watch, and AirPods simultaneously with up to 7.5W fast wireless charging.",
      price: 129.00,
      availability: "In Stock",
      shippingInfo: "Ships within 2-3 business days.",
      discount: "10% off for first-time buyers",
      rating: 4.7,
      reviews: 342,
      reviewsArray: [
        { user: "James Roberts", rating: 5, comment: "Very convenient for charging all my Apple devices at once." },
        { user: "Emma Collins", rating: 4, comment: "Great product but slightly overpriced." },
      ],
      variations: [
        { color: "Black", price: "$129", image: MockupImage },
      ],
      gallery: [MockupImage, MockupImage],
      dimensions: "190 x 90 x 15 mm",
      weight: "170g",
      warranty: "2 years manufacturer warranty",
      returnPolicy: "14 days return policy",
      faq: [
        { question: "Is it compatible with Samsung devices?", answer: "No, it's designed for Apple devices only." },
        { question: "Does it come with a power adapter?", answer: "Yes, it includes a 24W power adapter." },
      ],
      tags: { brandNew: true, popular: false, featured: false, newArrival: true },
    },
    {
      id: 21,
      name: "SanDisk Extreme Pro 128GB MicroSD Card",
      category: "Accessories",
      brand: "SanDisk",
      model: "Extreme Pro",
      priceRange: "34-54",
      image: MockupImage,
      description:
        "The SanDisk Extreme Pro 128GB MicroSD card delivers fast read and write speeds for high-resolution photos and 4K UHD video recording.",
      price: 49.00,
      availability: "In Stock",
      shippingInfo: "Ships within 1-2 business days.",
      discount: "5% off for orders over $50",
      rating: 4.8,
      reviews: 513,
      reviewsArray: [
        { user: "Oliver Bennett", rating: 5, comment: "Fast and reliable. Perfect for my GoPro." },
        { user: "Mia Foster", rating: 4, comment: "Works great, but it could be a bit cheaper." },
      ],
      variations: [
        { storage: "128GB", price: "$49", image: MockupImage },
      ],
      gallery: [MockupImage, MockupImage],
      dimensions: "15 x 11 x 1 mm",
      weight: "0.25g",
      warranty: "Lifetime limited warranty",
      returnPolicy: "30 days return policy",
      faq: [
        { question: "Is it suitable for 4K video recording?", answer: "Yes, it supports high-speed recording for 4K UHD." },
        { question: "Can it be used with drones?", answer: "Yes, it's ideal for drones and action cameras." },
      ],
      tags: { brandNew: true, popular: false, featured: true, newArrival: false },
    },
 
      {
        id: 22,
        name: "Sony WH-1000XM5 Noise Cancelling Headphones",
        category: "Headphones",
        brand: "Sony",
        model: "WH-1000XM5",
        priceRange: "349-399",
        image: MockupImage,
        description:
          "The Sony WH-1000XM5 offers industry-leading noise cancellation, superior sound quality, and up to 30 hours of battery life. Perfect for music lovers and travelers.",
        price: 379.00,
        availability: "In Stock",
        shippingInfo: "Ships within 1-2 business days.",
        discount: "10% off for students",
        rating: 4.9,
        reviews: 872,
        reviewsArray: [
          { user: "Lucas Wright", rating: 5, comment: "Best noise-canceling headphones I've ever used." },
          { user: "Ella Green", rating: 4, comment: "Great sound, but a bit bulky." },
        ],
        variations: [
          { color: "Black", price: "$379", image: MockupImage },
          { color: "Silver", price: "$379", image: MockupImage },
        ],
        gallery: [MockupImage, MockupImage],
        dimensions: "170 x 80 x 220 mm",
        weight: "254g",
        warranty: "1 year manufacturer warranty",
        returnPolicy: "30 days return policy",
        faq: [
          { question: "Do they support voice assistants?", answer: "Yes, they work with Google Assistant and Alexa." },
          { question: "Are they foldable?", answer: "Yes, the design allows for easy folding and storage." },
        ],
        tags: { brandNew: true, popular: true, featured: true, newArrival: false },
      },
      {
        id: 23,
        name: "Bose QuietComfort 45 Wireless Headphones",
        category: "Headphones",
        brand: "Bose",
        model: "QuietComfort 45",
        priceRange: "299-349",
        image: MockupImage,
        description:
          "The Bose QuietComfort 45 offers best-in-class noise cancellation, crystal-clear audio, and up to 24 hours of battery life, making it perfect for long listening sessions.",
        price: 329.00,
        availability: "In Stock",
        shippingInfo: "Ships within 1-2 business days.",
        discount: "5% off for Bose newsletter subscribers",
        rating: 4.8,
        reviews: 1023,
        reviewsArray: [
          { user: "Michael Baker", rating: 5, comment: "The noise cancellation is unbeatable." },
          { user: "Samantha Carter", rating: 4, comment: "Comfortable but the sound could be more vibrant." },
        ],
        variations: [
          { color: "Black", price: "$329", image: MockupImage },
        ],
        gallery: [MockupImage, MockupImage],
        dimensions: "190 x 165 x 80 mm",
        weight: "240g",
        warranty: "2 years manufacturer warranty",
        returnPolicy: "30 days return policy",
        faq: [
          { question: "Are they water-resistant?", answer: "No, they are not water-resistant." },
          { question: "Do they support wired connections?", answer: "Yes, they come with an audio cable for wired listening." },
        ],
        tags: { brandNew: true, popular: false, featured: false, newArrival: true },
      },
      {
        id: 24,
        name: "Jabra Elite 85h Wireless Headphones",
        category: "Headphones",
        brand: "Jabra",
        model: "Elite 85h",
        priceRange: "199-249",
        image: MockupImage,
        description:
          "The Jabra Elite 85h offers intelligent active noise cancellation, excellent battery life, and customizable sound profiles for an immersive listening experience.",
        price: 229.00,
        availability: "In Stock",
        shippingInfo: "Ships within 1-2 business days.",
        discount: "5% off for first-time buyers",
        rating: 4.7,
        reviews: 521,
        reviewsArray: [
          { user: "Benjamin Scott", rating: 5, comment: "Fantastic headphones, great value for money." },
          { user: "Grace Cooper", rating: 4, comment: "Good sound, but a bit tight on the ears." },
        ],
        variations: [
          { color: "Navy", price: "$229", image: MockupImage },
        ],
        gallery: [MockupImage, MockupImage],
        dimensions: "195 x 150 x 85 mm",
        weight: "296g",
        warranty: "2 years manufacturer warranty",
        returnPolicy: "30 days return policy",
        faq: [
          { question: "Do they support voice assistants?", answer: "Yes, they are compatible with Alexa, Siri, and Google Assistant." },
          { question: "Are they sweat-resistant?", answer: "Yes, they are IP52-rated for dust and water resistance." },
        ],
        tags: { brandNew: false, popular: true, featured: true, newArrival: false },
      },
      {
        id: 25,
        name: "Sennheiser Momentum 4 Wireless",
        category: "Headphones",
        brand: "Sennheiser",
        model: "Momentum 4",
        priceRange: "349-399",
        image: MockupImage,
        description:
          "The Sennheiser Momentum 4 Wireless delivers premium sound quality, adaptive noise cancellation, and an impressive 60 hours of battery life.",
        price: 379.00,
        availability: "In Stock",
        shippingInfo: "Ships within 2-3 business days.",
        discount: "10% off for audiophiles",
        rating: 4.9,
        reviews: 678,
        reviewsArray: [
          { user: "Nathan Edwards", rating: 5, comment: "Unbelievable battery life and sound quality." },
          { user: "Amelia Adams", rating: 4, comment: "Amazing headphones but a bit pricey." },
        ],
        variations: [
          { color: "Black", price: "$379", image: MockupImage },
        ],
        gallery: [MockupImage, MockupImage],
        dimensions: "200 x 180 x 90 mm",
        weight: "290g",
        warranty: "2 years manufacturer warranty",
        returnPolicy: "30 days return policy",
        faq: [
          { question: "Do they support fast charging?", answer: "Yes, 10 minutes of charge provides 4 hours of playback." },
          { question: "Are they foldable?", answer: "Yes, they are foldable for easy transport." },
        ],
        tags: { brandNew: true, popular: false, featured: true, newArrival: false },
      },
      {
        id: 26,
        name: "Beats Studio3 Wireless Over-Ear Headphones",
        category: "Headphones",
        brand: "Beats",
        model: "Studio3",
        priceRange: "249-349",
        image: MockupImage,
        description:
          "The Beats Studio3 Wireless offers high-performance noise-canceling technology, real-time audio calibration, and up to 22 hours of battery life with fast charging.",
        price: 299.00,
        availability: "In Stock",
        shippingInfo: "Ships within 1-2 business days.",
        discount: "5% off for Apple users",
        rating: 4.6,
        reviews: 892,
        reviewsArray: [
          { user: "Daniel Turner", rating: 5, comment: "Amazing sound, especially with bass-heavy tracks." },
          { user: "Chloe Lewis", rating: 4, comment: "Great sound but not very comfortable for long wear." },
        ],
        variations: [
          { color: "Red", price: "$299", image: MockupImage },
          { color: "Matte Black", price: "$299", image: MockupImage },
        ],
        gallery: [MockupImage, MockupImage],
        dimensions: "180 x 170 x 80 mm",
        weight: "260g",
        warranty: "1 year manufacturer warranty",
        returnPolicy: "30 days return policy",
        faq: [
          { question: "Do they support Apple devices?", answer: "Yes, they have seamless integration with Apple devices." },
          { question: "Can they be used with Android?", answer: "Yes, they are compatible with Android as well." },
        ],
        tags: { brandNew: true, popular: true, featured: false, newArrival: false },
      },
      {
        id: 27,
        name: "AKG K240 Studio Over-Ear Headphones",
        category: "Headphones",
        brand: "AKG",
        model: "K240 Studio",
        priceRange: "69-99",
        image: MockupImage,
        description:
          "The AKG K240 Studio headphones offer professional-grade sound for mixing and recording, with semi-open design for accurate sound representation.",
        price: 89.00,
        availability: "In Stock",
        shippingInfo: "Ships within 2-3 business days.",
        discount: "5% off for music producers",
        rating: 4.8,
        reviews: 403,
        reviewsArray: [
          { user: "Thomas King", rating: 5, comment: "Excellent for studio use. Very accurate sound." },
          { user: "Lily Thompson", rating: 4, comment: "Great sound, but the build could be more durable." },
        ],
        variations: [
          { color: "Black", price: "$89", image: MockupImage },
        ],
        gallery: [MockupImage, MockupImage],
        dimensions: "220 x 190 x 100 mm",
        weight: "240g",
        warranty: "2 years manufacturer warranty",
        returnPolicy: "30 days return policy",
        faq: [
          { question: "Are they good for casual listening?", answer: "They are designed for studio use but work well for casual listening too." },
          { question: "Do they support noise cancellation?", answer: "No, they are semi-open and don't have noise cancellation." },
        ],
        tags: { brandNew: false, popular: false, featured: true, newArrival: false },
      },
    ];
    
    export default products;
  

